baseURL = "http://example.org/"
languageCode = "en-us"
title = "Notes"
theme = "notty"

pygmentsUseClasses = true
pygmentsCodeFences = true

[permalinks]
posts = "/:sections/:year/:month/:day/:title/"
