baseURL = "https://peaceful-allen-79f773.netlify.com"
languageCode = "en-us"
title = "kw7oe"
theme = "my-theme"

pygmentsUseClasses = true
pygmentsCodeFences = true

summaryLength = 50

[permalinks]
posts = "/:sections/:year/:month/:day/:title/"
