baseURL = "http://blog.kaiwern.com/"
languageCode = "en-us"
title = "Kai Wern Choong"
theme = "my-theme"

pygmentsUseClasses = true
pygmentsCodeFences = true

[permalinks]
posts = "/:sections/:year/:month/:day/:title/"
