baseURL = "https://kaiwern.com"
languageCode = "en-us"
title = "kw7oe"
theme = "my-theme"

pygmentsUseClasses = true
pygmentsCodeFences = true

enableGitInfo = true
summaryLength = 50

[permalinks]
posts = "/:sections/:year/:month/:day/:slug/"
books = "/:sections/:title"

[build]
  writeStats = true

[markup]
  [markup.tableOfContents]
    endLevel = 1
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security.exec]
  osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$','(?i)^ASDF', '^HOME$']
