baseURL = "https://kaiwern.com"
languageCode = "en-us"
title = "kw7oe"
theme = "my-theme"

pygmentsUseClasses = true
pygmentsCodeFences = true

summaryLength = 50

[permalinks]
posts = "/:sections/:year/:month/:day/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
