#!/bin/bash

if [[ -z "$1" ]]; then
  echo "Please enter a git commit message"
  exit
fi

echo "Cleaning public directoy...."
cd public && find . -path ./.git -prune -o -exec rm -rf {} \; 2> /dev/null

echo "Run hugo..."
cd .. && hugo

echo "Committing to git"
cd public && git add . && git commit -m "$1" && git push origin master

echo "Successfully push to GitHub"
cd ..
